#dev,pro,h2,mysql,single,cluster
spring: 
  profiles: 
    active: dev,h2,single

vertx: 
  server: 
    host: 127.0.0.1
    port: 8000
    logActivity: true

chat: 
  version: 0.0.1

rsa: 
  client: 
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCllb7ysp+48Oj3XEQhP34O17PQTPVL75wgWMrYDR2dSIYA4hA18Evgc3K3PnHTLPQw0jDsjSIeR2K8Rta9BC06eAQ+jduaH64LspBeVzKEvvxTlXTMSaNol4+WJ7KFVGbBhhxoXdrhSYQXltgJg/+PAZ8xdNrDasrWiO1vCGSswIDAQAB
  server: 
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALcafkq2ZnNUOWvOlv843TNkG1kyvyY6Lt+Thl0PPCXmf0ZOnBp1KFADgBlTCrJl0tOvUsKPl0MBtd7khHSBm8HAD7NmSkiL9qE5ZohA/EG/SsgeGtN0EKHuIkPLIEy/quQBMn7ScW7ZPG1xWJgd0AQAAnZXPUiqacDvfUKwTASNAgMBAAECgYAIYyRJ09UZj1AaChqMklQ/mGRQT6zF2YBwKVfMR3hf3BEUbWFlLNyt3Zsujck9psBjhfJqix1IqnlkPl963rz9rPPcGYxMqnUPXd0Ii0Q1FcXV8qxZ7b8G2T008BiEb1N9xgwhJVZaBUF3M3zNlFegvp+wV0zp9qFnKuwRtVPtmQJBAP1jw37NCmb5/ZG+QYAnUX3f0hMcuGxrr96Y81B9INHNSCIZS8rI9+Su9kMk7G4oGQlkOeIOe+63HncunI/al2sCQQC4/V8nwO8dKjEil4cGscZNG4HaXAdob9pUxrLG68grRWHAk+VNoKyK2oQ7VYULI9EwOmFiJPhvAMPe3+gC9+nnAkEA8oGCXl7aL8fd2Jhfk8kNgwysv0Hjd1Bw1vdHFqdKu8Bd4tSW5xMDvMd+RLCX3q1dmNFlXGZEUijLbYEcscig1QJAOxTZBjZNaBAonzar7kxq3AeUAmxwBT/sCDVptbRqOr+vB7V0f8V4NeSyZMzccAFhdzi+D31lRvaEmDMEw6XwMwJBAJy8rDBXAcjXEcMedcOeAIKspOyc+2UDo+bNqZOHhaP1syB9EuFh499lVNTOKMvN8o0CT6fnAP3yr6IG6Zo4kDI=

